on:
  push:
    branches:
    - main

jobs:
  vite-build-production:
    name: Build w/ Vite
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/setup-node@v6
      with:
        node-version: "v25.x"
        cache-dependency-path: "package-lock.json"
    - run: npm ci
    - run: npm install
    - run: npx vite build --outDir docs
